<?php

function insertAdminAcct($values) {
    $stmt = $db->prepare("INSERT INTO admin-accts(first_name, last_name, email, username, hashed_password)
    VALUES(?,?,?,?,?)");
    $db->bind_param("isssss", $varName1, $varName2);
    $db->execute($stmt);
    $db->close();
    getQueryResultInfo();
}

function insertUserAcct($values) {
    $stmt = $db->prepare("INSERT INTO user-accts(username, hashed_password)
    VALUES(?,?)");
    $db->bind_param("is", $varName1, $varName2);
    $db->execute($stmt);
    $db->close();
    getQueryResultInfo();

    //return autogenerated username
    return $db->insert_id;
}

function insertPersonalInformation($values) {
    $stmt = $db->prepare("INSERT INTO personal-information(username, age, city, state, gender, cdl-app-holder, med-cert-deny)
    VALUES(?,?,?,?,?,?,?)");
    $db->bind_param("iisssss", $varName1, $varName2);
    $db->execute($stmt);
    $db->close();
    getQueryResultInfo();
}

function insertSurgeryMedication($values) {
    $stmt = mysqli_prepare($db, "INSERT INTO surgery-medication(username, surgery-name, surgery-description, medication-name, 
    medication-category)
    VALUES(?,?,?,?,?)");
    mysqli_stmt_bind_param($stmt, "issss", $varName);
    mysqli_stmt_execute($stmt);
    mysqli_stmt_bind_result($stmt, $result);
    getQueryResultInfo();
}

function insertConditionsChecklist($values) {
    $stmt = mysqli_prepare($db, "INSERT INTO conditions-checklist(username, head-brain, seisures-epilepsy, eye, 
    ear-hearing, heart-problems, heart-procedures, high-bp, high-cholesterol, breathing, lung, kidney, digestive, 
    blood-sugar, insulin, mental-health, fainting, dizz-head-numb-ting-mem, weight-loss, stroke-paralysis, 
    missing-limited-limb, neck-back, bone-mus-joing-nerve, bleeding, cancer, chronic-diseases, sleep, sleep-test 
    hospital, broken-bone, tobacco, alcohol, illegal-substance, fail-drug-test) 33
    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
    mysqli_stmt_bind_param($stmt, "isssssssssssssssssssssssssssssssss", $varName);
    mysqli_stmt_execute($stmt);
    mysqli_stmt_bind_result($stmt, $result);
    getQueryResultInfo();
}

function insertConditionComments($values) {
    $stmt = mysqli_prepare($db, "INSERT INTO condition-comments(username, other-conditions, conditions-comments)
    VALUES(?,?,?,?,?)");
    mysqli_stmt_bind_param($stmt, "issss", $varName);
    mysqli_stmt_execute($stmt);
    mysqli_stmt_bind_result($stmt, $result);
    getQueryResultInfo();
}

function getQueryResultInfo($db) {
    // http://php.net/manual/en/mysqli.affected-rows.php#116152
    // Report query information in associative array
    preg_match_all('/(\S[^:]+): (\d+)/', $db->info, $matches); 
    $infoArr = array_combine ($matches[1], $matches[2]);
    var_export($infoArr);

    //error if no rows affected
    if($db->affected_rows === 0) 
        exit('No rows affected');
    else if($db->affected_rows === -1) 
        exit('DB query error');
}

